[package]
name = "termios"
version = "0.2.2"
authors = ["David Cuddeback <david.cuddeback@gmail.com>"]
description = "Safe bindings for the termios library."
license = "MIT"
homepage = "https://github.com/dcuddeback/termios-rs"
repository = "https://github.com/dcuddeback/termios-rs"
documentation = "http://dcuddeback.github.io/termios-rs/termios/"
readme = "README.md"
keywords = ["termios", "tty", "terminal", "posix"]

[dependencies]
libc = "0.2"
ioctl-rs = "0.1.5"
