#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

//! The code in this crate contains the raw bindings for termios, automatically generated by
//! [bindgen][]. Before continuing any further, please make sure [termios][] is not the crate you
//! really are looking for.
//!
//! [bindgen]: https://docs.rs/bindgen/latest/bindgen/
//! [termios]: https://docs.rs/bindgen/latest/termios/

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
